
# tap repositories and their packages

tap homebrew/core
brew abseil
brew adns
brew ansible
brew aom
brew apr
brew apr-util
brew argon2
brew aribb24
brew asdf
brew aspell
brew autoconf
brew automake
brew bdw-gc
brew berkeley-db
brew boost
brew brotli
brew c-ares
brew ca-certificates
brew cairo
brew carthage
brew ccat
brew cffi
brew cjson
brew clipper
brew cmocka
brew cocoapods
brew composer
brew coreutils
brew ctags
brew curl
brew dav1d
brew direnv
brew ffmpeg
brew firebase-cli
brew flac
brew fontconfig
brew freetds
brew freetype
brew frei0r
brew fribidi
brew gd
brew gdbm
brew gettext
brew ghostscript
brew ghq
brew giflib
brew git
brew git-flow
brew glib
brew gmp
brew gnupg
brew gnutls
brew gobject-introspection
brew graphite2
brew guile
brew harfbuzz
brew highlight
brew highway
brew icu4c
brew imagemagick@6
brew imath
brew iproute2mac
brew jansson
brew jbig2dec
brew jemalloc
brew jpeg
brew jpeg-turbo
brew jpeg-xl
brew jq
brew jsoncpp
brew krb5
brew lame
brew leptonica
brew libarchive
brew libass
brew libassuan
brew libavif
brew libb2
brew libbluray
brew libcbor
brew libev
brew libevent
brew libffi
brew libfido2
brew libgcrypt
brew libgpg-error
brew libidn
brew libidn2
brew libksba
brew libmetalink
brew libmicrohttpd
brew libnghttp2
brew libogg
brew libpng
brew libpq
brew libpthread-stubs
brew librist
brew libsamplerate
brew libsndfile
brew libsodium
brew libsoxr
brew libssh2
brew libtasn1
brew libtiff
brew libtool
brew libunibreak
brew libunistring
brew libusb
brew libusb-compat
brew libuv
brew libvidstab
brew libvmaf
brew libvorbis
brew libvpx
brew libx11
brew libxau
brew libxcb
brew libxdmcp
brew libxext
brew libxrender
brew libyaml
brew libzip
brew little-cms2
brew lua
brew lz4
brew lzo
brew m4
brew mackup
brew macos-term-size
brew mas
brew mbedtls
brew mecab
brew mint
brew mosh
brew mpdecimal
brew mpg123
brew mysql
brew ncurses
brew nettle
brew nghttp2
brew node
brew node-build
brew nodenv
brew npth
brew oniguruma
brew opencore-amr
brew openexr
brew openjpeg
brew openldap
brew openssl@1.1
brew openssl@3
brew opus
brew p11-kit
brew pango
brew pcre
brew pcre2
brew peco
brew perl
brew php
brew pinentry
brew pinentry-mac
brew pixman
brew pkg-config
brew pngquant
brew protobuf
brew protobuf@21
brew pth
brew pup
brew pycparser
brew python-certifi
brew python-cryptography
brew python-dateutil
brew python-docopt
brew python-jinja
brew python-lxml
brew python-markupsafe
brew python-packaging
brew python-pyparsing
brew python-pytz
brew python-setuptools
brew python@3.10
brew python@3.11
brew python@3.12
brew python@3.8
brew python@3.9
brew pyyaml
brew rav1e
brew rbenv
brew readline
brew reattach-to-user-namespace
brew rtmpdump
brew rtx
brew rubberband
brew ruby
brew ruby-build
brew sdl2
brew six
brew snappy
brew speex
brew sqlite
brew srt
brew svt-av1
brew swiftformat
brew swiftgen
brew tcl-tk
brew tesseract
brew the_silver_searcher
brew thefuck
brew theora
brew tidy-html5
brew tig
brew tmux
brew tree
brew unar
brew unbound
brew unixodbc
brew utf8proc
brew vercel-cli
brew vim
brew volta
brew w3m
brew webp
brew wget
brew wp-cli
brew x264
brew x265
brew xcodegen
brew xmlstarlet
brew xorgproto
brew xvid
brew xz
brew yarn
brew yq
brew zeromq
brew zimg
brew zlib
brew zsh
brew zstd

tap homebrew/cask
cask 1password
cask alfred
cask alt-tab
cask android-studio
cask appcleaner
cask bartender
cask bettertouchtool
cask betterzip
cask caffeine
cask charles
cask choosy
cask cleanshot
cask docker
cask dropbox
cask figma
cask firefox
cask google-chrome
cask google-japanese-ime
cask hammerspoon
cask haroopad
cask imageoptim
cask intellij-idea
cask istat-menus
cask iterm2
cask kaleidoscope
cask keyboardcleantool
cask libreoffice
cask little-snitch
cask mamp
cask mysqlworkbench
cask orbstack
cask proxyman
cask qlmarkdown
cask quicklook-csv
cask quicklook-json
cask scriptql
cask sequel-ace
cask shortcat
cask sketch
cask suspicious-package
cask transmit
cask vagrant
cask vagrant-manager
cask virtualbox
cask visual-studio-code
cask vivaldi
cask xcodes
cask zeplin

tap homebrew/cask-versions
cask figma-beta
cask google-chrome-canary

tap argon/mas

tap peripheryapp/periphery
cask periphery

tap rcmdnk/file
brew brew-file

tap stripe/stripe-cli
brew stripe

# Other Homebrew packages
brew protobuf@3.7

# App Store applications
appstore 1130783329 Archiver 3 (3.0.9)
appstore 412536790 CodeBox (1.6)
appstore 1024640650 CotEditor (4.7.1)
appstore 1388020431 DevCleaner (2.5.1)
appstore 682658836 GarageBand (10.4.10)
appstore 408981434 iMovie (10.4)
appstore 409183694 Keynote (13.2)
appstore 441258766 Magnet (2.14.0)
appstore 784801555 Microsoft OneNote (16.80)
appstore 409203825 Numbers (13.2)
appstore 409201541 Pages (13.2)
appstore 1529448980 Reeder (5.4)
appstore 1504940162 RocketSim (12.4.1)
